export interface StripeMongoosePluginOptions {
  secretKey: string
  firstnameField: string
  lastnameField: string
  emailField: string
  phoneField: string
  addressLine1Field: string
  addressLine2Field: string
  addressPostalCodeField: string
  addressCityField: string
  addressStateField: string
  addressCountryField: string
  paymentMethodTypes: string[]
  localeField: string
  invoiceLang:
    | 'auto'
    | 'bg'
    | 'cs'
    | 'da'
    | 'de'
    | 'el'
    | 'en'
    | 'en-GB'
    | 'es'
    | 'es-419'
    | 'et'
    | 'fi'
    | 'fil'
    | 'fr'
    | 'fr-CA'
    | 'hr'
    | 'hu'
    | 'id'
    | 'it'
    | 'ja'
    | 'ko'
    | 'lt'
    | 'lv'
    | 'ms'
    | 'mt'
    | 'nb'
    | 'nl'
    | 'pl'
    | 'pt'
    | 'pt-BR'
    | 'ro'
    | 'ru'
    | 'sk'
    | 'sl'
    | 'sv'
    | 'th'
    | 'tr'
    | 'vi'
    | 'zh'
    | 'zh-HK'
    | 'zh-TW'
}
